version: "2.0"
services:
  backend:
    build: ./backend
    container_name: finacx-api
    restart: always
    environment:
        TZ: America/Sao_Paulo
        SPRING_BOOT_ENVIRONMENT: Production
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - app-finacx
  db:
    image: mariadb:10.3
    container_name: finacx-db
    ports:
      - 3306:3306
    environment:
      TZ: America/Sao_Paulo
      MARIADB_ROOT_PASSWORD: admin
      MARIADB_USER: docker
      MARIADB_PASSWORD: docker
      MARIADB_DATABASE: finacx
    networks:
      - app-finacx
  frontend:
    build: ./frontend
    container_name: finacx-front
    restart: always
    ports:
      - 3000:3000
    command: 'npm start'
    links:
      - backend
    depends_on:
      - backend
    networks:
      - app-finacx
networks:
  app-finacx:
    driver: bridge